language: php

sudo: false

matrix:
  include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm-3.6
      sudo: required
      dist: trusty
      group: edge
    - php: hhvm-3.9
      sudo: required
      dist: trusty
      group: edge
    - php: hhvm-3.12
      sudo: required
      dist: trusty
      group: edge

before_install:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'hhvm.jit = false' >> /etc/hhvm/php.ini ; fi

install:
  - if [ "$TRAVIS_PHP_VERSION" != "5.2" ]; then travis_retry composer install --no-interaction --prefer-source; fi

script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.2" ]; then phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" != "5.2" ]; then vendor/bin/phpunit; fi
